services:
  video-platform:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres   # service name, not localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PW: postgres
      DB_NAME: videoplatform

  postgres:
    image: postgres:15
    container_name: postgres-video-platform
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videoplatform
    ports:
      - "5432:5432"
